site_name: 內科手冊
site_description: "值班、臨床推理、學習資源、血液腫瘤科"
site_url: https://htlin222.github.io/manual/
edit_uri: edit/master/docs/
repo_url: https://github.com/htlin222/manual
repo_name: htlin222/manual
copyright: Copyright &copy; 2023 -  Hsieht-Ting Lin M.D. 🦎
announcement: 這個網站目前什麼都沒有
extra:
  social:
    - icon: octicons/link-24
      link: https://www.kfsyscc.org/m/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  custom_dir: overrides
  favicon: images/favicon.ico
  logo: images/logo.png
  language: zh-TW
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - announce.dismiss
    - header.autohide
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.expand
    - navigation.prune
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips
    - content.action.edit
    - content.action.view
plugins:
  - search
  - markmap
  - alias
  - meta-descriptions:
      export_csv: false
      quiet: false
      enable_checks: false
      min_length: 50
      max_length: 160
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: true
  - social:
      cards_font: Noto Sans TC
  - tags
  - ezlinks
  - table-reader:
      base_path: "config_dir"
      data_path: "docs/tables/"
      search_page_directory: True
      allow_missing_files: False
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  - bibtex:
    # in config_dir
      bib_file: "https://api.zotero.org/groups/4751389/collections/VQMBK9ZP/items?format=bibtex"
      csl_file: "jama.csl"
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  # [Pymdown Extensions - PyMdown Extensions Documentation](https://facelessuser.github.io/pymdown-extensions/)
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
