site_name: 和信內科手冊
theme:
  name: material
  favicon: images/favicon.ico
  logo: images/logo.svg
  palette:
    primary: teal
  language: zh-TW
  features:
    - tabs
repo_url: https://github.com/htlin222/kfyscc-manual
repo_name: htlin222/kfyscc-manual
plugins:
  - git-revision-date
  - search
markdown_extensions:
  - abbr
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - footnotes
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - meta


