name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: |
          pip install mkdocs-material \
          pillow cairosvg mkdocs-ezlinks-plugin \
          mkdocs-table-reader-plugin \
          mkdocs-glightbox \
          mkdocs-enumerate-headings-plugin \
          mkdocs-markmap \
          mkdocs-section-index \
          mkdocs-alias-plugin \
          mkdocs-awesome-pages-plugin \
          mkdocs-git-revision-date-localized-plugin \
          mkdocs-meta-descriptions-plugin \
          mkdocs-bibtex \
          pypandoc
      - run: mkdocs gh-deploy --force
